name: SPM
on: 
  pull_request:
    paths: 'bids_prov/**'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r dev-requirements.txt
      - name: Test SPM parser on explicit_mask
        run: |
          curl -LJO https://raw.githubusercontent.com/incf-nidash/nidmresults-examples/master/spm_explicit_mask/batch.m
          python -m bids_prov.spm_parser --input_file batch.m --output_file explicit_mask.json

      - name: Test SPM Parser on groups OLS
        run: |
          curl -LJO https://raw.githubusercontent.com/incf-nidash/nidmresults-examples/master/spm_group_ols/batch.m
          python -m bids_prov.spm_parser --input_file batch.m --output_file ols.json
